### ISSUE TITLE
Problem when refreshing git repo

### ISSUE THREAD

**Issue by GillesMocellin** [salt-formulas/salt-formula-letsencrypt#1] opened 2017-01-28 11:00 UTC
Modifications on the letsencrypt Git repo is often not a simple fast-forward.
in install.sls, the git.latest fails.
We need something like a force_fetch option.
I tried, it worked, but with a strange warning.

My modification :
```
diff --git a/letsencrypt/install.sls b/letsencrypt/install.sls
index 31b279b..6876a50 100644
--- a/letsencrypt/install.sls
+++ b/letsencrypt/install.sls
@@ -8,3 +8,4 @@ letsencrypt-client-git:
     - name: https://github.com/letsencrypt/letsencrypt
     - target: {{ letsencrypt.cli_install_dir }}
     - force_reset: True
+    - force_fetch: True
```

The Warning :
```
    git_|-letsencrypt-client-git_|-https://github.com/letsencrypt/letsencrypt_|-latest:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
        duration:                                                                                                                                                                         1691.61
        name:
            https://github.com/letsencrypt/letsencrypt
        result:
            True
        start_time:
            10:50:29.373780                                                                                                                                                           warnings:
            - 'force_fetch' is an invalid keyword argument for 'git.latest'. If you were trying to pass additional data to be used in a template context, please populate 'con
text' with 'key: value' pairs. Your approach will work until Salt Carbon is out. Please update your state files.
```

**Comment by fpytloun** [comment] 2017-01-28 14:27
Hello Gilles,
the problem is also in dropping letsencrypt tool in favor of certbot (living here: https://github.com/certbot/certbot)
This formula should get updated to use certbot and to support installation from package (as it's already available eg. in Debian Stretch and Jessie backports) which should be preferred method. Also there are probably more fixes that needs to be done.

@michaelkuty has also a fork which should be probably merged with upstream? https://github.com/michaelkuty/salt-formula-letsencrypt

**Comment by fpytloun** [comment] 2017-01-28 15:04
This may fix the issue and switch to certbot.
Also it allows three installation options:
- package (default for Debian)
- URL to certbot-auto (default for RHEL)
- Docker container

I haven't tested that yet so help is appreciated here :-)

**Comment by GillesMocellin** [comment] 2017-01-28 15:25
Hi !

Of course, the preferred way is certainly to switch to certbot, and use the packaged version if available.
As I use Debian, it is for me.

Containers are certainly not for all use cases : I have an OpenVZ container for web apps, and certainly don't want to run a Docker container inside an OpenVZ one !

Thanks for your work, I don't know if I will be able to test it easily.

**Comment by michaelkuty** [comment] 2017-01-29 12:30
Yes, in my fork is ,,remote" feature for distributing certificates from one central place like CA which is big change between this formula.

**Comment by fpytloun** [comment] 2017-01-31 14:14
So, my change is complete and mostly tested.
Please review and give me feedback.

- added support for multiple installation methods
- refactored metadata model
- readme

**Closed** 2017-02-01 12:05 UTC
